PREFIX  og:   <http://ogp.me/ns#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase84678>
              <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor>  ?v0 .
    ?v0       og:tag                ?v1 ;
              rdf:type              ?v3 ;
              sdo:text              ?v4 .
    ?v2       og:tag                ?v1
  }
