PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { ?v0  <http://db.uwaterloo.ca/~galuc/wsdbm/gender>  <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> ;
         <http://xmlns.com/foaf/familyName>  ?v1 ;
         <http://xmlns.com/foaf/givenName>  ?v2 ;
         sdo:email             ?v3 ;
         <http://db.uwaterloo.ca/~galuc/wsdbm/userId>  ?v5
  }
