PREFIX  og:   <http://ogp.me/ns#>
PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { ?v0  og:tag                <http://db.uwaterloo.ca/~galuc/wsdbm/Topic129> ;
         sdo:caption           ?v2 ;
         sdo:expires           ?v3 .
    ?v4  <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor>  ?v0 ;
         <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate>  ?v5
  }
