PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { ?v2  rdf:type              <http://db.uwaterloo.ca/~galuc/wsdbm/Genre5> .
    ?v1  <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre>  ?v2 .
    ?v0  <http://purl.org/goodrelations/includes>  ?v1 .
    ?v1  sdo:expires           ?v4 ;
         sdo:text              ?v5 .
    ?v6  <http://db.uwaterloo.ca/~galuc/wsdbm/likes>  ?v1
  }
