PREFIX  og:   <http://ogp.me/ns#>
PREFIX  rev:  <http://purl.org/stuff/rev#>
PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { ?v0  og:tag             <http://db.uwaterloo.ca/~galuc/wsdbm/Topic111> ;
         rev:hasReview      ?v2 ;
         sdo:contentRating  ?v6 ;
         sdo:description    ?v7 ;
         sdo:keywords       ?v8 .
    ?v2  rev:rating         ?v3 ;
         rev:reviewer       ?v4 ;
         rev:totalVotes     ?v5
  }
