PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { ?v0  <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre>  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre88> ;
         sdo:description       ?v1 ;
         sdo:editor            ?v2
  }
