PREFIX  og:   <http://ogp.me/ns#>
PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { ?v0  <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre>  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre52> ;
         og:title              ?v1 ;
         sdo:contentRating     ?v2
  }
