PREFIX  og:   <http://ogp.me/ns#>
PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { ?v0  <http://xmlns.com/foaf/homepage>  <http://db.uwaterloo.ca/~galuc/wsdbm/Website2182> .
    ?v2  <http://purl.org/goodrelations/includes>  ?v0 .
    ?v0  og:title              ?v3 ;
         sdo:keywords          ?v4 ;
         sdo:text              ?v5 ;
         <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre>  ?v6 .
    ?v7  <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor>  ?v0
  }
