PREFIX  og:   <http://ogp.me/ns#>
PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { ?v0  <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre>  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre127> ;
         <http://xmlns.com/foaf/homepage>  ?v1 ;
         og:tag                ?v2 ;
         sdo:keywords          ?v3
  }
