PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { ?v0  sdo:eligibleRegion    <http://db.uwaterloo.ca/~galuc/wsdbm/Country11> ;
         <http://purl.org/goodrelations/includes>  ?v1 .
    ?v2  <http://purl.org/goodrelations/offers>  ?v0 .
    ?v0  <http://purl.org/goodrelations/price>  ?v3 ;
         <http://purl.org/goodrelations/serialNumber>  ?v4 ;
         <http://purl.org/goodrelations/validFrom>  ?v5 ;
         <http://purl.org/goodrelations/validThrough>  ?v6 ;
         sdo:eligibleQuantity  ?v8 ;
         sdo:priceValidUntil   ?v10 .
    ?v1  sdo:author            ?v7
  }
