PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  sdo:  <http://schema.org/>

SELECT  *
WHERE
  { ?v0  <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre>  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre73> ;
         <http://xmlns.com/foaf/homepage>  ?v1 ;
         rdf:type              ?v2 ;
         sdo:description       ?v3 ;
         sdo:expires           ?v4 .
    ?v1  sdo:url               ?v5
  }
